# Generated by Django 4.2.1 on 2023-05-12 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Light',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('on', models.BooleanField()),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('creation', models.DateField()),
                ('light', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eid_light.light')),
            ],
        ),
    ]
