# Generated by Django 4.2.1 on 2023-05-15 18:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eid_light', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='creation',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='slug',
        ),
        migrations.AddField(
            model_name='friends',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friends',
            name='ident',
            field=models.TextField(default=django.utils.timezone.now, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friends',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
