# Generated by Django 4.2.1 on 2023-05-15 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eid_light', '0002_remove_friends_creation_remove_friends_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='ident',
            field=models.IntegerField(max_length=20, unique=True),
        ),
    ]
