# Generated by Django 4.2.1 on 2023-05-16 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eid_light', '0004_alter_friends_ident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='light',
            name='slug',
            field=models.TextField(max_length=255, unique=True),
        ),
    ]
