# Generated by Django 4.2.1 on 2023-05-16 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eid_light', '0005_alter_light_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='light',
            name='slug',
        ),
        migrations.AddField(
            model_name='light',
            name='ident',
            field=models.TextField(default=datetime.time, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
