# Generated by Django 4.2.1 on 2023-05-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eid_light', '0007_user_light_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='light',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='friends',
            name='on',
            field=models.BooleanField(default=False),
        ),
    ]
