# Generated by Django 4.2.1 on 2023-06-01 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eid_light', '0008_light_public_alter_friends_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='light',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
